### PR TITLE
[RFC Implementation] Bypass gpg validation of packages if the registry does not provide any keys

### LINKED ISSUE #266: RFC: Provider GPG Key Handling in OpenTF Registry: Temporary Non-Failure Response to Missing Public Keys
### Summary

This RFC attempts to temporarily solve the issue where provider keys are not known by provider registries, causing OpenTF to fail provider validation. 

To allow users to carry on working with OpenTF, we set out to provide a process in which the end users of OpenTF can work around this temporary issue until a solution for providing keys in the registry is completed.

### Problem Statement

With the launch of OpenTF, we've recognized the necessity to introduce a new registry for the associated provider ecosystem. This fresh registry, designed to specifically cater to OpenTF, faces a foundational challenge: we currently do not possess copies of all the GPG keys that provider authors utilize to sign their packages.

### User-facing description

By introducing a new environment variable `OPENTF_ENFORCE_GPG_VALIDATION`, end users can control the functionality of GPG validation.

This environment variable only takes effect if the provider metadata downloaded from the registry does not provide any keys for validation. If the provider registry supplies keys, then validation will still occur.

- When set to `false`, this environment variable acts to bypass the GPG validation checks. (default)
- When set to `true`, this environment variable acts to enforce the GPG validation checks.

### Technical Description

By introducing a new temporary flow to the current Package authentication process, we can control if validation occurs or not.

See the original code here: https://github.com/opentffoundation/opentf/blob/b36ff25ea7b922b0a7efd883ebeee9275b56945f/internal/getproviders/package_authentication.go#L370-L380

If the provider registry has supplied a list of keys for the provider version download, we will always validate those.

If the provider registry has not supplied any keys, we check if the environment variable is set to `true` (enforcing), and if so we will attempt to validate any keys we can (most likely resulting in an error). Otherwise if the variable is `false` (default) we will ignore validation for those providers and allow them to be used.

#### Flow Diagram

```mermaid
graph TD;

    Start["Start"] -->|Retrieve Provider Metadata| A[Does provider registry supply keys?]
    A -->|Yes| B[Perform GPG Validation]
    A -->|No| C[Is OPENTF_ENFORCE_GPG_VALIDATION set to true?]
    C -->|Yes| D[Attempt GPG Validation]
    D --> Error["Error"]
    C -->|No| E[Bypass GPG Validation]
    B --> End["End"]
    E --> End
```

### Rationale and alternatives

If we did not implement this, at the moment that providers are downloaded for new projects or provider upgrades, the validation will fail causing the command to fail.

This is needed to ensure that opentf can be compatible with the new provider registry **temporarily** until we can source the GPG keys for each package author.

### Downsides

The downsides of this project is that validation may not occur for some packages by default until the provider registry populates all it's GPG keys

### Unresolved Questions

- Do we want to set a deadline of a timeframe or even a release version to make sure that this feature is removed?

### Related Issues

#258 - Replace registry

### Proof of Concept
See #309

### PR DESCRIPTION
**Pull request by Yantrio**
RFC: #266 

Summary:
- Introduced a dedicated function `shouldEnforceGPGValidation()` to determine if GPG validation should be enforced.
- GPG validation is now prioritized if signing keys are provided, ensuring a secure-by-default approach.
- Addressed a minor typo in comments for clarity.

Details:
- The new method simplifies the logic in `AuthenticatePackage()` and can be reused if needed in other parts of the code.
- By checking for the presence of signing keys first, we ensure that validation takes precedence over environment variable configurations.
- A TODO has been added to discuss how unvalidated packages should be represented in the result, suggesting the potential use of a hardcoded "UNKNOWN" value.

Note: Further consideration is required on how best to represent unvalidated packages in the authentication result.

Fixes #266 

## Target Release

1.6.0

### UPGRADE NOTES

- IMPORTANT: When downloading providers through the opentf registry, skip validation for packages that do not have a GPG key attached. This can be overridden by setting `OPENTF_ENFORCE_GPG_VALIDATION`. By setting this environment variable to `"true"`, opentf will attempt to validate all package downloads.
-

### CODE REVIEW

File: internal/getproviders/package_authentication_test.go [hunk 1]
```diff
@@ -365,13 +365,18 @@ func TestSignatureAuthentication_success(t *testing.T) {
 		t.Run(name, func(t *testing.T) {
 			// Location is unused
 			location := PackageLocalArchive("testdata/my-package.zip")
+			//
+			//providerSource, err := tfaddr.ParseProviderSource("testdata/my-package.zip")
```
Comment (mbialon) [inline internal/getproviders/package_authentication_test.go:369]: Did you want to use it in the tests? None of the `NewSignatureAuthentication` invocations test passing a provider source.

**Review by mbialon — APPROVED** [review]

File: internal/getproviders/package_authentication.go [hunk 2]
```diff
@@ -359,15 +378,50 @@ type signatureAuthentication struct {
...
+
+	if !shouldValidate {
+		// As this is a temporary measure, we will log a warning to the user making it very clear what is happening
+		// and why. This will be removed in a future release.
+		log.Printf("[WARN] Skipping GPG validation of provider package %s as no keys were provided by the registry. See https://github.com/opentffoundation/opentf/pull/309 for more information.", location)
+
+		// construct an empty keyID to indicate that we are not validating and return no errors
+		// this is to force a successful authentication
+		// TODO: discuss if this key should be hardcoded to a value such as "UNKNOWN"?
+		return &PackageAuthenticationResult{result: signingSkipped, KeyID: ""}, nil
```
Comment (yaronya) [inline internal/getproviders/package_authentication.go:420]: Hard coded value sounds more reasonable ("SKIPPED" perhaps?)

File: internal/command/init.go [hunk 3]
```diff
@@ -816,7 +816,11 @@ func (c *InitCommand) getProviders(ctx context.Context, config *configs.Config,
 				keyID = c.Colorize().Color(fmt.Sprintf(", key ID [reset][bold]%s[reset]", keyID))
 			}
 
-			c.Ui.Info(fmt.Sprintf("- Installed %s v%s (%s%s)", provider.ForDisplay(), version, authResult, keyID))
+			if authResult != nil && authResult.SigningSkipped() {
+				c.Ui.Warn(fmt.Sprintf("- Installed %s v%s, however signature validation was skipped due to the registry not containing GPG keys for this provider", provider.ForDisplay(), version))
```
Comment (eranelbaz) [inline internal/command/init.go:820]: WDYT About dropping the "however"?

File: internal/getproviders/package_authentication.go [hunk 4]
```diff
@@ -359,15 +378,50 @@ type signatureAuthentication struct {
...
 func (s signatureAuthentication) AuthenticatePackage(location PackageLocation) (*PackageAuthenticationResult, error) {
+	shouldValidate, err := s.shouldEnforceGPGValidation()
+	if err != nil {
+		return nil, fmt.Errorf("error determining if GPG validation should be enforced for pacakage %s: %s", location.String(), err.Error())
+	}
+
+	if !shouldValidate {
+		// As this is a temporary measure, we will log a warning to the user making it very clear what is happening
+		// and why. This will be removed in a future release.
+		log.Printf("[WARN] Skipping GPG validation of provider package %s as no keys were provided by the registry. See https://github.com/opentffoundation/opentf/pull/309 for more information.", location)
```
Comment (eranelbaz) [inline internal/getproviders/package_authentication.go:415]: can we put it in a proper README?

**Review by eranelbaz — COMMENTED** [review]
I'm a bit out of scope regarding the implementation and discussions, but game some user-facing ideas

File: internal/getproviders/package_authentication.go [hunk 5]
```diff
@@ -359,15 +378,50 @@ type signatureAuthentication struct {
...
+		Document:       document,
+		Signature:      signature,
+		Keys:           keys,
+		ProviderSource: source,
+	}
+}
+
+func (s signatureAuthentication) shouldEnforceGPGValidation() (bool, error) {
+	// we should enforce validation for all provider sources that are not the default provider registry
+	if s.ProviderSource != nil && s.ProviderSource.Hostname != tfaddr.DefaultProviderRegistryHost {
```
Comment (yaronya) [inline internal/getproviders/package_authentication.go:392]: Consider adding a test to cover this piece of logic, as it has a quite few conditions in it

File: internal/getproviders/package_authentication_test.go (hunk 1 above)
Comment (Yantrio) [reply internal/getproviders/package_authentication_test.go:370]: For now I was going to keep the tests simple and not use it in the tests.

File: internal/command/init.go (hunk 3 above)
Comment (Yantrio) [reply internal/command/init.go:820]: I think that's a good idea 👍

File: internal/getproviders/package_authentication.go (hunk 4 above)
Comment (Yantrio) [reply internal/getproviders/package_authentication.go:415]: Part of the reason I wanted to link to the issue here is that the issue is where most of the discussion is ongoing and it's evergreen automatically.

Also people can join in the conversation around this too. If we had a README file then this could easily get missed or go un-updated for a long term.

File: internal/getproviders/package_authentication.go (hunk 2 above)
Comment (Yantrio) [reply internal/getproviders/package_authentication.go:420]: I've given this some thought lately, and since I added the `signingSkipped` result, this keyID is never read. I think leaving it as an empty string and removing the TODO may be best here. WDYT?

Comment (yaronya) [reply internal/getproviders/package_authentication.go:420]: SGTM

**Review by yaronya — APPROVED** [review]

**Review by tomasmik — APPROVED** [review]
